### ISSUE TITLE
Cannot show Chinese characters

### ISSUE THREAD

**Issue by EldersJavas** [caderek/polytopia-languages#19]
## Cannot show Chinese characters

I started the translation [here](https://github.com/EldersJavas/polytopia-languages)

And I find the game connot show the characters all the time.

Please tell me how to do

**Comment by caderek** [comment]
Closing, as working Chinese translation was added: https://github.com/caderek/polytopia-languages/blob/master/templates/cn.json

**Comment by AdminHcat** [comment]
> Closing, as working Chinese translation was added: https://github.com/caderek/polytopia-languages/blob/master/templates/cn.json

Chinese characters cannot be displayed in full. Some characters will be displayed as □, squares, 
And in general, the Simplified Chinese code is zh_cn,  Traditional Chinese is zh_tw, but now cn is occupied, maybe we should adjust the naming rules

**Comment by WluhWluh** [comment]
Unfortunately, the current version of the game only supports displaying Japanese Kanji, not the full Simplified or Traditional Chinese character set.  I'm the one who made this Chinese translation, which mixes Simplified and Traditional characters and avoids some common but unsupported characters to ensure that "□" doesn't appear.  This might introduces some statement weirdness, but that's the best I can do.
